import Eye from '@/components/Eye/Eye';
import styles from '@/styles/Home.module.css';
import Head from 'next/head';
import React, { useState } from 'react';

export default function Home() {
  const [show, setShow] = useState<boolean>(false);

  return (
    <React.Fragment>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.test}>
        <Eye show={show} onClick={() => setShow(!show)} />
      </div>
    </React.Fragment>
  );
}
