// Import Next
import dynamic from 'next/dynamic';
import Head from 'next/head';
import React from 'react';

// Import Composants
const MapComponent = dynamic(() => import('@/components/MapComponent/MapComponent'), { ssr: false });

export default function Quest() {
  return (
    <React.Fragment>
      <Head>
        <title>Quest | Customs</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <script src="https://kit.fontawesome.com/bf63fdfe50.js"></script>
      </Head>
      <MapComponent />
    </React.Fragment>
  );
}
