// Import Next
import dynamic from 'next/dynamic';
import Head from 'next/head';

// Import Composants
const Map = dynamic(() => import('@/components/map/map'), { ssr: false });

export default function Quest() {
  return (
    <>
      <Head>
        <title>Quest | Customs</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <script src="https://kit.fontawesome.com/bf63fdfe50.js"></script>
      </Head>
      <Map />
    </>
  );
}
